pipeline {
    agent 'master'

    stages {
        stage('Checkout') {
            steps {
              git credentialsId: "${github_creds}", url: "${github_repo}"
            }
        }
        stage('selenium connection string') {
            steps {
                sh 'ls -lrt'
            }
        }
        stage('selenium connection string') {
            steps {
                sh 'ls -lrt'
            }
        }
        stage('selenium connection string') {
            steps {
                sh 'ls -lrt'
            }
        }
    }
}
